//Extract users from Tealium to .csv
//2015-11-05
//Note: Uses Html-elements, must view the "user management"-list
//Note: div[15] is only true for the first list viewed after relog

var log_users =[];
var y =[];


tmp_lenght = $x("/html/body/div[15]/div[2]/div/table/tbody/tr/td/div[2]/div[2]/div[2]/div/div/label/div/div/div[2]/div/div[2]").length;

for (i = 1; i < tmp_lenght; i++) { 
//get the name
y = $x("/html/body/div[15]/div[2]/div/table/tbody/tr/td/div[2]/div[2]/div[2]/div/div[" + i + "]/label/div/div/div[2]/div/div[2]");
y[0] = y[0].innerHTML+",";
//get the email
z = $x("/html/body/div[15]/div[2]/div/table/tbody/tr/td/div[2]/div[2]/div[2]/div/div[" + i + "]/label/div/div/div[2]/div/input");
y[0] += z[0].value;
log_users[i-1] = y[0];
}


var data = [["###csv generated by CQ###", "", Date().substring(0, 33)], ["1", "2", "3"]];
data[1] = log_users;


var csvContent = "data:text/csv;charset=utf-8,";
data.forEach(function(infoArray, index){

   dataString = infoArray.join("\n");
   csvContent += index < data.length ? dataString+ "\n" : dataString;

}); 




var encodedUri = encodeURI(csvContent);
var link = document.createElement("a");
link.setAttribute("href", encodedUri);
link.setAttribute("download", "tealium_users.csv");

link.click(); 
