



//Extract Turn-Key Tags from Tealium to .csv
//2015-11-05
//Note: Uses Html-elements, must view the "user management"-list in Tealium IQ
//Usage: Paste into Dev-console
//Note: div[15] is only true for the first list viewed after relog

var log_tags =[];
var y =[];

tmp_lenght = $x("/html/body/div[15]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/span").length;

for (i = 1; i < tmp_lenght; i++) { 
y = $x("/html/body/div[15]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div[" + i + "]/div/div");
var tmp = y[0].innerHTML;
tmp = tmp.match(/\>(.*?)\</g); 
log_tags[i-1] = tmp[0].replace(/\>|</g, '');
}


var data = [["###csv generated by CQ###", "", Date().substring(0, 33)], ["name2", "city2", "more info"]];
data[1] = log_tags;


var csvContent = "data:text/csv;charset=utf-8,";
data.forEach(function(infoArray, index){

   dataString = infoArray.join("\n");
   csvContent += index < data.length ? dataString+ "\n" : dataString;

}); 




var encodedUri = encodeURI(csvContent);
var link = document.createElement("a");
link.setAttribute("href", encodedUri);
link.setAttribute("download", "tealium_marketplace_tags.csv");

link.click(); 

